name: spooky
description: Minimalist application to write stories, notes, diary!
publish_to: none
version: 1.3.9+108
environment:
  sdk: ">=2.17.0 <3.0.0"

# flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog: ^1.6.3
  animated_clipper: ^0.2.0+2
  animations: ^2.0.3
  awesome_notifications: ^0.7.4+1
  azlistview: ^2.0.0
  bubble_lens:
    git:
      url: git@github.com:juniorise/bubble_lens.git
      ref: main
  cached_network_image: ^3.2.1
  community_material_icon: ^5.9.55
  copy_with_extension: ^5.0.0
  cupertino_icons: ^1.0.4
  desktop_window: ^0.4.0
  dynamic_color: ^1.3.0
  easy_localization: ^3.0.1
  cloud_firestore: ^4.2.0
  firebase_analytics: ^10.0.7
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.7
  flutter_cupertino_datetime_picker:
    git:
      url: git@github.com:juniorise/flutter_cupertino_datetime_picker.git
      ref: 3.0.2
  flutter_facebook_auth: ^4.4.0+1
  facebook_app_events:
    git:
      url: git@github.com:juniorise/flutter_facebook_app_events.git
      ref: 1.0.3
  flutter_markdown: ^0.6.10+1
  flutter_phoenix: ^1.0.0
  flutter_quill: ^6.1.6
  flutter_screen_lock: ^7.0.4
  flutter_secure_storage: ^7.0.1
  flutter_sticky_header: ^0.6.3
  flutter_weather_bg_null_safety:
    git:
      url: git@github.com:juniorise/flutter_weather_bg_null_safety.git
      ref: 1.0.0
  fluttertoast: ^8.0.9
  fuzzy: ^0.4.0-nullsafety.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.2
  googleapis: ^9.1.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  in_app_purchase: ^3.0.6
  json_annotation: ^4.5.0
  just_audio: ^0.9.24
  local_auth: ^2.1.0
  logger: ^1.1.0
  material_color_utilities: ^0.1.5
  miniplayer: ^1.0.1
  package_info_plus: ^1.3.0
  path: ^1.8.1
  path_provider: ^2.0.10
  provider: ^6.0.3
  quick_actions: ^1.0.0
  rect_getter: ^1.1.0
  responsive_builder: ^0.4.2
  restart_app: ^1.1.0+1
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  swipeable_page_route: ^0.2.6
  timezone: ^0.9.0
  tuple: ^2.0.0
  url_launcher: ^6.1.2
  wave: ^0.2.0
  encrypt: ^5.0.1
  html_character_entities: ^1.0.0+1
  simple_animations: ^5.0.0+2
  launch_review: ^3.0.1
  in_app_update: ^4.0.1
  flutter_custom_tabs: ^1.0.4
  flutter_cache_manager: ^3.3.0
  photo_view: ^0.14.0
  objectbox: ^1.5.0
  objectbox_flutter_libs: any
  flat_buffers: ^2.0.5
  device_info_plus: ^7.0.0
  app_settings: ^4.1.6
  flutter_signin_button: ^2.0.0
  visibility_detector: ^0.3.3
  flutter_countdown_timer: ^4.1.0
  day_night_time_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.6.2
  flutter_slidable: ^2.0.0
  dismissible_page: ^0.7.3
  image_cropper: ^3.0.0
  new_version: ^0.3.1
  string_similarity: ^2.0.0
  scroll_to_index: ^3.0.1
  confetti: ^0.7.0
  dio: ^4.0.6
  japx: ^2.0.4
  firebase_crashlytics: ^3.0.7
  easy_localization_loader: ^1.0.0
  string_validator: ^0.3.0
  popover: ^0.2.6+3
  navigation_history_observer: ^1.1.0

  # unused:
  # objectbox_sync_flutter_libs: for ObjectBox Sync
  # injectable: ^1.5.3
  # open_file: ^3.2.1
  # scroll_to_index: ^3.0.1
  # stacked_services: ^0.8.25
  # visibility_detector: ^0.3.3
  # intl: ^0.17.0
  # flutter_keyboard_visibility: ^5.2.0
  # open_settings: ^2.0.2
  # googleapis_auth: ^1.3.1
  # simple_animations: ^4.0.2
  # expandable_text: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
  copy_with_extension_gen: ^5.0.0
  objectbox_generator:
    git:
      url: "https://github.com/juniorise/objectbox-dart.git"
      path: generator
      ref: 1.6.2

  # unused:
  # injectable_generator: ^1.5.3
  # change_app_package_name: ^1.1.0
  # flutter_native_splash: ^2.2.0+1
  # dependency_validator: ^3.2.0 # pub run dependency_validator

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/licenses/
    - translations/
    - assets/illustrations/
    - assets/emoji-64/
    - assets/sounds/sounds.json
    - assets/fonts/Quicksand/
